name: docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and push Sphinx to GitHub pages
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
