name: "Build Doc"
on:
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        activate-environment: test
        channel-priority: true
        environment-file: devtools/conda-envs/espaloma.yaml
        auto-activate-base: false
        use-mamba: true

    - name: Install package
      shell: bash -l {0}
      run: |
        python -m pip install --no-deps .
    - name: Compile
      shell: bash -l {0}
      run: |
        python -m pip install sphinx sphinx-rtd-theme numpydoc
        cd docs && make html && cd _build/html && echo 'espaloma.wangyq.net' > CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.event.pull_request.merged == true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
